#!/usr/bin/env python

import sys
import re

start = int(sys.argv[1]) + 1
end = int(sys.argv[2]) + 2

def load_seq_from_fasta():
	seq = sys.stdin.read()
	patern = r'^>.*$'
	filtered_seq = re.sub(patern, '', seq, flags=re.MULTILINE)
	filtered_seq = filtered_seq.lower().strip('\n').replace('\n','')
	return filtered_seq

filtered_seq = load_seq_from_fasta()
print(filtered_seq[start:end])