#!/usr/bin/env python

import sys
import re
# import textwrap

# def reverse(s): # NENÍ POTŘEBA cyklím přes reversed(seq)
#     str = ""
#     for i in s:
#         str = i + str
#     return str

trans_table = {
				'a': 't',
				't': 'a',
				'g': 'c',
				'c': 'g',
				}

# lines = sys.stdin.readlines()
# def translate(seq): # tohle otočí a přeloží každou řádku zvlášť
# 	transcrpt = ''
# 	for line in seq:
# 		l = reverse(line)
# 		transcrpt += ''.join(trans_table[i] for i in l if i.lower() in trans_table)
# 	return transcrpt

# print(textwrap.fill(translate(lines).strip('\n'), width = 60))
# print(translate(lines).strip('\n'))

def load_seq_from_fasta():
	seq = sys.stdin.read()
	patern = r'^>.*$'
	filtered_seq = re.sub(patern, '', seq, flags=re.MULTILINE)
	filtered_seq = filtered_seq.lower().strip('\n').replace('\n','')
	return filtered_seq

def translate(seq):
	return ''.join(trans_table[c] for c in reversed(seq))
	# return ''.join(c for c in reversed(seq))

seq = load_seq_from_fasta()
print(translate(seq))